version: '3.8'
services:
  mycourtdb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=courtdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    hostname: mycourtdb
    container_name: mycourtdb
    networks:
      - springcourts
volumes:
  db:
    driver: local

networks:
  springcourts:
    driver: bridge